### ISSUE TITLE
ReferenceError: nodemon is not defined while executed gulp

### ISSUE THREAD

**Issue by xinshouke** [Loogeek/douban-Vue#1]
I executed the command gulp,but I found the below error
       ReferenceError: nodemon is not defined
After I install grunt-nodemon,the  error was the same as like the above

**Comment by Loogeek** [comment]
先尝试npm install 安装全部包，如果还有该告警请安装gulp-nodemon 而不是grunt-nodemon

**Comment by xinshouke** [comment]
@Loogeek Sorry, I also found my fault and is closing it first
